//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCCare.WS_SportMillion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hbcom.vn/", ConfigurationName="WS_SportMillion.SportMillionSoap")]
    public interface SportMillionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Check(string Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Dereg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dereg(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInfo(string Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Reg_VNP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg_VNP(string UserName, string IP, string Signature, MyCCare.WS_SportMillion.ChannelType mChannel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/DeReg_VNP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeReg_VNP(string UserName, string IP, string Signature, MyCCare.WS_SportMillion.ChannelType mChannel);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hbcom.vn/")]
    public enum ChannelType {
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        IVR,
        
        /// <remarks/>
        WEB,
        
        /// <remarks/>
        WAP,
        
        /// <remarks/>
        USSD,
        
        /// <remarks/>
        CLIENT,
        
        /// <remarks/>
        API,
        
        /// <remarks/>
        UNSUB,
        
        /// <remarks/>
        CSKH,
        
        /// <remarks/>
        MAXRETRY,
        
        /// <remarks/>
        SUBNOTEXIST,
        
        /// <remarks/>
        SYSTEM,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SportMillionSoapChannel : MyCCare.WS_SportMillion.SportMillionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SportMillionSoapClient : System.ServiceModel.ClientBase<MyCCare.WS_SportMillion.SportMillionSoap>, MyCCare.WS_SportMillion.SportMillionSoap {
        
        public SportMillionSoapClient() {
        }
        
        public SportMillionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SportMillionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportMillionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportMillionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Check(string Signature) {
            return base.Channel.Check(Signature);
        }
        
        public string Reg(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Reg(ChannelType, Signature, CommandCode);
        }
        
        public string Dereg(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Dereg(ChannelType, Signature, CommandCode);
        }
        
        public System.Data.DataTable GetInfo(string Signature) {
            return base.Channel.GetInfo(Signature);
        }
        
        public string Reg_VNP(string UserName, string IP, string Signature, MyCCare.WS_SportMillion.ChannelType mChannel) {
            return base.Channel.Reg_VNP(UserName, IP, Signature, mChannel);
        }
        
        public string DeReg_VNP(string UserName, string IP, string Signature, MyCCare.WS_SportMillion.ChannelType mChannel) {
            return base.Channel.DeReg_VNP(UserName, IP, Signature, mChannel);
        }
    }
}
